### ISSUE TITLE
Unable to add links: 'Settings' object has no attribute 'SITE_URL'

### ISSUE THREAD

**Issue by brysonsteck** [dmptrluke/django-markdownfield#14]
Hello! I am running into an issue where this plugin is throwing an error when I try to post a new Model Object with a markdownfield. Specifically, it seems it's having issues when trying to parse URLs. It happens when I try adding the URL manually or using the editor's function. When the links are removed, everything POSTs just fine. Am I missing some install or configuration step?

Here is the traceback from Django:
```
Request Method: POST
Request URL: http://localhost:8000/admin/blog/blog/add/

Django Version: 4.0.4
Python Version: 3.9.12
Installed Applications:
['fontawesomefree',
 'markdownfield',
 'blog.apps.BlogConfig',
 'projects.apps.ProjectsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/bryson/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1885, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1220, in save_model
    obj.save()
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1620, in execute_sql
    for sql, params in self.as_sql():
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1547, in as_sql
    value_rows = [
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1548, in <listcomp>
    [
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1549, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/bryson/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1497, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/bryson/.local/lib/python3.9/site-packages/markdownfield/models.py", line 98, in pre_save
    clean = cleaner.clean(dirty)
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/sanitizer.py", line 184, in clean
    return self.serializer.render(filtered)
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/_vendor/html5lib/serializer.py", line 398, in render
    return "".join(list(self.serialize(treewalker)))
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/html5lib_shim.py", line 705, in serialize
    for stoken in super().serialize(treewalker, encoding):
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/_vendor/html5lib/serializer.py", line 265, in serialize
    for token in treewalker:
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/linkifier.py", line 520, in __iter__
    yield from self.handle_a_tag(token_buffer)
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/linkifier.py", line 481, in handle_a_tag
    attrs = self.apply_callbacks(attrs, False)
  File "/home/bryson/.local/lib/python3.9/site-packages/bleach/linkifier.py", line 254, in apply_callbacks
    attrs = cb(attrs, is_new)
  File "/home/bryson/.local/lib/python3.9/site-packages/markdownfield/util.py", line 34, in format_link
    c = urlparse(settings.SITE_URL)
  File "/home/bryson/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 88, in __getattr__
    val = getattr(self._wrapped, name)

Exception Type: AttributeError at /admin/blog/blog/add/
Exception Value: 'Settings' object has no attribute 'SITE_URL'
```

The model in concern:
```
class Project(models.Model):
  title = models.CharField(max_length=200)
  current = models.BooleanField(default=True)
  overview = models.TextField()
  description = MarkdownField(rendered_field='text_rendered',use_editor=False, use_admin_editor=True, validator=VALIDATOR_STANDARD)
  text_rendered = RenderedMarkdownField()
  image = models.ImageField(upload_to='projects/static/projects/images/')
```

Let me know if you need more information.

**Comment by benjaoming** [comment]
A bit of an ambiguous headline, but see the README under "Implementation" where it says to configure `SITE_URL`:

https://github.com/dmptrluke/django-markdownfield#implementation

It's used here:
https://github.com/dmptrluke/django-markdownfield/blob/master/markdownfield/util.py#L34

**Comment by brysonsteck** [comment]
Adding `SITE_URL` to the settings fixed my issue, I guess I glossed over it while implementing. Thanks!

**Comment by Spiewart** [comment]
Sorry, I know this is a closed and old issue. My internal links are being rendered as external when I'm running a development server.

I've got a base + local vs production settings file.

In my settings/local.py my SITE_URL is set:
`SITE_URL = "http://localhost:3000"`

The template renders my internal link as:
`<a href="/djangoapp/create/" target="_blank" class=" external" rel="nofollow noopener noreferrer">djangomodel</a>`

When I highlight the href in Chrome developer tools it shows: http://localhost:3000/djangoapp/create/

When I set my local.py SITE_URL to: www.mywebapp.com and then hard-coded the markdown links to: www.mywebapp.com/djangoapp/create/ it correctly determined that the link was internal.

I can't figure out how to configure it to detect my internal links as internal in development.

Appreciate any thoughts on how to configure this correctly.

**Comment by benjaoming** [comment]
> The template renders my internal link as:
`<a href="/djangoapp/create/" target="_blank" class=" external" rel="nofollow noopener noreferrer">djangomodel</a>`

That looks like the correct behavior?

> When I highlight the href in Chrome developer tools it shows: http://localhost:3000/djangoapp/create/

You have to clarify this a bit more. What is the actual HTML that was outputted?

**Comment by Spiewart** [comment]
> > The template renders my internal link as:
> > `<a href="/djangoapp/create/" target="_blank" class=" external" rel="nofollow noopener noreferrer">djangomodel</a>`
> 
> That looks like the correct behavior?
> 
> > When I highlight the href in Chrome developer tools it shows: http://localhost:3000/djangoapp/create/
> 
> You have to clarify this a bit more. What is the actual HTML that was outputted?

This is the actual HTML output:

`<a href="/djangoapp/create/" target="_blank" class=" external" rel="nofollow noopener noreferrer">djangomodel</a>`

When I change the href to `href="http://localhost:3000/djangoapp/create/"`, the HTML output is: 
`<a href="http://localhost:3000/djangoapp/create"> djangomodel </a>`

This renders correctly as an internal link. I think I am seeing the problem, in that when I put the internal link in my .md file as /djangoapp/create/, my application routes the URL correctly by opening a new tab with the correct internal page, but the markdown is processed as if it is an internal link.

Any tips on how to include relative links without hard-coding them? The issue is that the hard-coded URL will be different in development vs production.

**Comment by benjaoming** [comment]
I think you should go ahead and open an issue about this. It sounds like the support for internal links does not respect the SITE_URL setting (or maybe you can pinpoint it in a new issue) ?

**Comment by Spiewart** [comment]
> I think you should go ahead and open an issue about this. It sounds like the support for internal links does not respect the SITE_URL setting (or maybe you can pinpoint it in a new issue) ?

Done. 

https://github.com/dmptrluke/django-markdownfield/issues/35

I developed a workaround to achieve the desired behavior. 

Any feedback is appreciated.
